
	<!-- EXISTING PHONE /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->

	<input type="hidden" name="base[0][phoneNew]" id="phoneNew" value="<?= ($phoneNew) ? 'NEW' : 'USE' ?>">
	<div style="margin-top: 0;">
		<div class="panel panel-default <?= ($phoneNew) ? '' : 'visible' ?>" id="phoneNewInfo0">
		    <div class="panel-heading">
		        <h3 class="panel-title"><?= $this->translate('Use phone number on file') ?></h3>
		    </div>
		    <div class="panel-body">
		        <div class="input-group select">
		            <span class="input-group-addon"><i class="icon-phone"></i></span>
		            <?php $formCardData->get('cardDataUserPhoneNumberId')->setAttribute('class', 'form-control'); ?>
		            <?php echo $this->makeElementArray($this->formSelect($formCardData->get('cardDataUserPhoneNumberId')), 'cardData', 0); ?>
		        </div>
		    </div>
		     <div class="panel-body footer-body">
		        <div class="panel-footer">
		            <span class="link"><a target="javascript:void(0);" id="add_new_phone"><?= $this->translate('Add New Phone') ?></a></span>
		        </div>
		    </div>
		</div>

		<!-- NEW PHONE ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->

		<div class="panel panel-default <?= ($phoneNew) ? 'visible' : '' ?>" id="phoneNewInfo1">
		    <div class="panel-heading">
		        <h3 class="panel-title"><?= $this->translate('Add new phone number') ?></h3>
		    </div>
		    <div class="panel-body">
		        <h5 class="split-two">Phone Type</h5>
		        <h5 class="split-two">Phone Number</h5>
		
		        <div class="input-group split select">
	                <span class="input-group-addon"><i class="icon-list-ul"></i></span>
	                <select name="telephone[0][phoneType]" required="required">
	                    <option value="day">Day</option>
	                    <option value="evening">Evening</option>
	                    <option value="home">Home</option>
	                    <option value="business">Business</option>
	                    <option value="mobile">Mobile</option>
	                    <option value="fax">Fax</option>
	                    <option value="other">Other</option>
	                </select>
	            </div>

	            <?php echo $this->partial('application/partials/form-text-div-span', 
	                  array('element'     => $formTelephone->get('phoneNumber'), 
	                        'divClass'    => 'input-group split', 
	                        'spanClass'   => 'input-group-addon',
	                        'iconClass'   => 'icon-phone',
	                        'inputClass'  => 'form-control',
	                        'placeHolder' => '',
	                        'group'       => 'telephone',
	                        'num'         => 0,
	            )); ?>
			</div>
		    <div class="panel-body footer-body">
		        <div class="panel-footer">
		            <span class="link"><a target="javascript:void(0);" id="submit_cancel_phone"><?= $this->translate('Use Phone Number On File') ?></a></span>
		        </div>
		    </div>
    	</div>
		
		<!-- EXISTING ADDRESS ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->

		<input type="hidden" name="base[0][addrNew]" id="addrNew" value="<?= ($addrNew) ? 'NEW' : 'USE' ?>">
    	<div class="panel panel-default <?= ($addrNew) ? '' : 'visible' ?>" id="addrNewInfo0">
		    <div class="panel-heading">
		        <h3 class="panel-title"><?= $this->translate('Use address on file') ?></h3>
		    </div>
		    <div class="panel-body">
		        <div class="input-group select">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <?php $formCardData->get('cardDataUserBillingAddressId')->setAttribute('class', 'form-control'); ?>
		            <?php echo $this->makeElementArray($this->formSelect($formCardData->get('cardDataUserBillingAddressId')), 'cardData', 0); ?>
		        </div>
		    </div>
		     <div class="panel-body footer-body">
		        <div class="panel-footer">
		             <span class="link"><a target="javascript:void(0);" id="add_new_address"><?= $this->translate('Add New Address') ?></a></span>
		        </div>
		    </div>
		</div>

		<!-- NEW ADDRESS /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->

		<div class="panel panel-default <?= ($addrNew) ? 'visible' : '' ?>" id="addrNewInfo1">
		    <div class="panel-heading">
		        <h3 class="panel-title"><?= $this->translate('Add new address') ?></h3>
		    </div>
		    <div class="panel-body">
		    	<h5 class="split-two">Address</h5>
		    	<h5 class="split-two">Suite/Apt</h5>
		        <div class="input-group split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <input type="text" name="addr[0][address1]" class="form-control">
		        </div>
		        <div class="input-group split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <input type="text" name="addr[0][address2]" class="form-control">
		        </div>
		    </div>
		    <div class="panel-body">
		    	<h5 class="split-two">City</h5>
		    	<h5 class="split-two">State/Province</h5>
		        <div class="input-group split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <input type="text" name="addr[0][cityName]" id="city" list="worldCities" class="form-control">
		        </div>
		        <div class="input-group split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <input type="text" name="addr[0][stateProvName]" title="State&#x2F;Province&#x20;Name&#x20;or&#x20;Abbreviation" class="form-control">
		        </div>
		    </div>
		    <div class="panel-body">
		    	<h5 class="split-two">Zip/Postal</h5>
		    	<h5 class="split-two">Country</h5>
		        <div class="input-group split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <input type="text" name="addr[0][zipPostalCode]" id="zipPostalCode" class="form-control">
		        </div>
		        <div class="input-group select split">
		            <span class="input-group-addon"><i class="icon-map-marker"></i></span>
		            <?php $formPaymentBase->get('country')->setAttribute('class', 'form-control'); ?>
		            <?php echo $this->makeElementArray($this->formSelect($formPaymentBase->get('country')), 'base', 0); ?>
		        </div>
		    </div>
		    <div class="panel-body footer-body">
		        <div class="panel-footer">
		             <span class="link"><a target="javascript:void(0);" id="submit_cancel_address"><?= $this->translate('Use Address On File') ?></a></span>
		        </div>
		    </div>
		</div>
	</div>
<script>
$(document).ready(function() {
    $('#add_new_phone').on("click", function(e) {
        $('#phoneNewInfo0').hide();
        $('#phoneNewInfo1').show();
        $('#phoneNew').val('NEW');
    });

    $('#submit_cancel_phone').on("click", function(e) {
        $('#phoneNewInfo1').hide();
        $('#phoneNewInfo0').show();
        $('#phoneNew').val('USE');
    });

    $('#add_new_address').on("click", function(e) {
        $('#addrNewInfo0').hide();
        $('#addrNewInfo1').show();
        $('#addrNew').val('NEW');
    });

    $('#submit_cancel_address').on("click", function(e) {
        $('#addrNewInfo1').hide();
        $('#addrNewInfo0').show();
        $('#addrNew').val('USE');
    });
});
</script>
