<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Malicious CSRF Site</title>
    </head>
    <body>
        <p>This is a sample of how a malicious CSRF attack might take place. If
        your site is vulnerable, then a submission was just made to the
        guestbook without the user's knowledge or consent.</p>

        <p><a href="/guestbook">Click here</a> to go to the guestbook and check.</p>
        <iframe src="/csrf-poster" height="0" width="0" style="border:0;" />
    </body>
</html>
